import type { ExtensionMessage, ExtensionResponse } from '../types/messages';
import type { FormField, PageContext } from '../types/models';
import { createFormField } from '../services/form/fieldDetection';
import { normalizeText } from '../utils/text';

const selectorFor = (element: Element, index: number) => { if ((element as HTMLElement).id) return `#${CSS.escape((element as HTMLElement).id)}`; const name = element.getAttribute('name'); if (name) return `${element.tagName.toLowerCase()}[name="${CSS.escape(name)}"]`; return `${element.tagName.toLowerCase()}:nth-of-type(${index + 1})`; };
const labelFor = (element: Element) => { const id = element.getAttribute('id'); const explicit = id ? document.querySelector(`label[for="${CSS.escape(id)}"]`)?.textContent : ''; const parent = element.closest('label')?.textContent; const sibling = element.previousElementSibling?.textContent; return normalizeText(explicit || parent || element.getAttribute('aria-label') || element.getAttribute('placeholder') || sibling || element.getAttribute('name') || 'Unnamed field'); };

function capture(): PageContext {
  const text = normalizeText(document.body?.innerText || '');
  const metadata = { title: document.title, sourceUrl: location.href, applicationUrl: location.href, description: text.slice(0, 10000), remoteType: /hybrid/i.test(text) ? 'hybrid' as const : /remote/i.test(text) ? 'remote' as const : /on[- ]site/i.test(text) ? 'on-site' as const : 'unknown' as const };
  return { title: document.title, url: location.href, htmlSnapshot: document.documentElement.outerHTML.slice(0, 120000), extractedText: text.slice(0, 20000), metadata, capturedAt: new Date().toISOString() };
}
function detect(): FormField[] {
  return [...document.querySelectorAll('input, textarea, select, [contenteditable="true"]')].filter((el) => !(el as HTMLInputElement).disabled && (el as HTMLElement).offsetParent !== null).map((element, index) => { const input = element as HTMLInputElement; const type = element.tagName.toLowerCase() === 'textarea' ? 'textarea' : element.tagName.toLowerCase() === 'select' ? 'select' : element.getAttribute('contenteditable') === 'true' ? 'contenteditable' : input.type || 'text'; return createFormField({ selector: selectorFor(element, index), label: labelFor(element), name: input.name || input.id || '', type, value: input.value || element.textContent?.trim() || '', required: input.required || element.getAttribute('aria-required') === 'true' }); });
}
function fill(fields: Array<{ selector: string; value: string }>) { let filled = 0; for (const field of fields) { const element = document.querySelector(field.selector) as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | HTMLElement | null; if (!element) continue; if (element instanceof HTMLSelectElement) { const option = [...element.options].find((item) => item.text.toLowerCase().includes(field.value.toLowerCase()) || item.value.toLowerCase() === field.value.toLowerCase()); element.value = option?.value || field.value; } else if (element.isContentEditable) element.textContent = field.value; else { const setter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(element), 'value')?.set; setter?.call(element, field.value); if (!setter) (element as HTMLInputElement).value = field.value; } element.dispatchEvent(new Event('input', { bubbles: true })); element.dispatchEvent(new Event('change', { bubbles: true })); filled += 1; } return filled; }

chrome.runtime.onMessage.addListener((message: ExtensionMessage, _sender, sendResponse: (response: ExtensionResponse) => void) => { try { if (message.type === 'CAPTURE_PAGE_CONTEXT') sendResponse({ ok: true, context: capture() }); else if (message.type === 'DETECT_FORM_FIELDS') sendResponse({ ok: true, fields: detect() }); else if (message.type === 'FILL_FORM_FIELDS') sendResponse({ ok: true, filled: fill(message.fields) }); else sendResponse({ ok: true, pong: true }); } catch (error) { sendResponse({ ok: false, error: error instanceof Error ? error.message : 'Content script failed' }); } return true; });
